#!/usr/local/bin/ruby 
#
# psync - Parallel rsync client/server utility
#
# Chad Kerner                    chad.kerner@gmail.com
# Senior Storage Engineer         ckerner@illinois.edu
# Storage Enabling Technologies
# National Center for Supercomputing Applications
# University of Illinois Urbana-Champaign
#

require 'socket'
require 'json'
require 'fileutils'
require 'optparse'
require 'securerandom'
require 'socket'


options = { port: 8812, depth: 3, threads: 4, debug: false, summary: false }
OptionParser.new do |opts|
  opts.banner = "Usage: psync server [options] | client [options] | log <pathname|token id> | tail <pathname|token id> | state | errors "
  opts.on("--port PORT", "Server/client port (default: 8812)") { |v| options[:port] = v.to_i }
  opts.on("--source DIR", "Source directory (server)") { |v| options[:source_dir] = v }
  opts.on("--depth DEPTH", "Depth to search (server, default: 3)") { |v| options[:depth] = v.to_i }
  opts.on("--remote SERVERS", "Comma-separated list of remote servers or a file containing server list (server)") do |v|
    if File.file?(v)
      options[:remote_servers] = File.readlines(v).map(&:chomp)
    else
      options[:remote_servers] = v.split(',')
    end
  end
  opts.on("--remote-path PATH", "Remote path for synchronization (server)") { |v| options[:remote_path] = v }
  opts.on("--server IP", "Server IP address (client)") { |v| options[:server] = v }
  opts.on("--threads THREADS", "Number of client threads to run (client, default: 4)") { |v| options[:threads] = v.to_i }
  opts.on("--summary", "Enable individual client log summary ") { options[:summary] = true }
  opts.on("--debug", "Enable debug mode ") { options[:debug] = true }
  opts.on("--dry-run", "Enable dry-run mode. No transfers. (server)") { options[:dryrun] = true }
  opts.on("--help", "Display help") do
    puts opts
    exit
  end
end.parse!

FileUtils.mkdir_p('server_logs')
FileUtils.mkdir_p('client_logs')
FileUtils.mkdir_p('transfer_logs')

class Server
  def initialize(options)
    @port = options[:port]
    @source_dir = options[:source_dir]
    @depth = options[:depth]
    @remote_servers = options[:remote_servers]
    @remote_path = options[:remote_path]
    @debug = options[:debug]
    @dryrun = options[:dryrun]
    @jobs = Queue.new
    @total_jobs = 0
    @log_file = "server_logs/server.log"
    FileUtils.touch(@log_file)
    @active_clients = 0
    @server_running = true
    @all_jobs_dispatched = false
    @return_codes = Hash.new(0)
    @dispatched_jobs = Hash.new { |h, k| h[k] = Hash.new }

    # THESE ARE     |---------------> skip newer files on receiver
    # THE NECESSARY ||--------------> directories
    # OPTIONS FOR   |||-------------> copy symlinks
    # THE SYNC TO   ||||------------> copy hard links
    # COPY ALL OF   |||||-----------> copy permissions
    # THE DATA.     ||||||----------> copy owner
    # IF YOU ARE    |||||||---------> copy group
    # GOING TO      ||||||||--------> copy ACLs
    # MODIFY THEM   |||||||||-------> copy XATTRs
    # IT IS AT YOUR ||||||||||------> show progress 
    # OWN RISK.     |||||||||||-----> copy device files
    #               ||||||||||||----> run in verbose mode
    # USE --dry-run |||||||||||||---> Add a 2nd to log every file 
    # TO VERIFY     |||||||||||||   
    @rsync_opts = '-udlHpogAXPDvv'
  end

  def log(message)
    puts message
    File.open(@log_file, 'a') { |f| f.puts("[#{Time.now}] #{message}") }
  end

  def generate_server_report
    return if @return_codes.nil? || @return_codes.empty?
    log("--- Transfer Summary Report ---")
    log("Total rsync transfers: #{@return_codes.values.sum}")
    @return_codes.sort.each do |code, count|
      log("Return Code #{code}: #{count} occurrences")
    end
    log("-------------------------------")
  end

  def build_jobs
    log("Building job queue...")
    (0..@depth).each do |level|
      dirs = `find #{@source_dir} -mindepth #{level} -maxdepth #{level} -type d`.split("\n")
      dirs.each do |dir|
        relative_path = dir.sub(@source_dir, '').sub(%r{^/}, '')
        @remote_servers.each do |server|
          recursive = (level == @depth) ? '-r' : ''
	  do_xfers = @dryrun ? '-n' : ''
          identifier = SecureRandom.hex(8)
          log_file = "transfer_logs/transfer_#{identifier}.log"
          rsync_cmd = "rsync #{@rsync_opts} #{recursive} #{do_xfers} #{dir}/ #{server}:#{@remote_path}/#{relative_path}/ &>> #{log_file}"
          @jobs.push({ command: rsync_cmd, identifier: identifier, server: server, path: dir })
	  @total_jobs += 1
          log("Generated rsync command for #{dir} -> #{server}:#{@remote_path}/#{relative_path} with ID #{identifier}") if @debug
        end
      end
    end
    log("Job queue built with #{@jobs.size} tasks.")
    @all_jobs_dispatched = true
  end

  def handle_request( client, request )
    case request['command']
    when 'work'
      if @jobs.empty?
         response = { status: 'no work' }
      else
        job = @jobs.pop
        @active_clients += 1
        @dispatched_jobs[client.peeraddr.last][job[:identifier]] = job[:path]
        log("Dispatched: #{client.peeraddr.last} #{job[:identifier]} #{job[:path]}")
        response = { status: 'work', command: job[:command], identifier: job[:identifier], path: job[:path] }
      end

    when 'status'
      response = { status: 'state', clients: @active_clients }
      log("Dispatched: #{client.peeraddr.last} #{job[:identifier]} #{job[:path]}")
    when 'done'
      @dispatched_jobs[client.peeraddr.last].delete(request['identifier'])
      log(" Completed: #{client.peeraddr.last} #{request['identifier']} #{request['path']} RC: #{request['return_code']}")
      rc = request['return_code']
      @return_codes[rc] += 1
  
      @active_clients -= 1
      response = { status: 'ok' }
    when 'end'
      exit 0
    when 'state'
      response = { status: 'state' , total_xfers: @total_jobs, left_xfers: @jobs.size, clients: @active_clients, dispatched: @dispatched_jobs, return_codes: @return_codes }
    end
    return response
  end

  def start
    begin
      server = TCPServer.new(@port)
    rescue Errno::EADDRINUSE
      log("Error: Port #{@port} is already in use. Exiting.")
      exit 1
    end

    Thread.new { build_jobs }
    log("Server started on port #{@port}")
    @return_codes ||= {}
    loop do
      break unless @server_running
      Thread.start(server.accept) do |client|
        begin
          data = client.gets
          if data
            request = JSON.parse(data.strip) rescue nil
            response = request ? handle_request(client,request) : { error: 'Invalid JSON' }
          else
            response = { error: 'No data received' }
          end
  	client.puts response.to_json 
        rescue StandardError => e
          client.puts({ error: e.message }.to_json)
        ensure
          client.close
        end

        if @all_jobs_dispatched && @jobs.empty? && @active_clients == 0
          log("All jobs processed. Shutting down server.")
          @server_running = false
          generate_server_report
        end
      end
    end
  end

end

class Client
  @@return_codes = Hash.new(0)
  @@thread_count = 0
  @@thread_mutex = Mutex.new

  def initialize(options)
    @server = options[:server]
    @port = options[:port]
    @debug = options[:debug]
    @threads = options[:threads]
    @summary = options[:summary]
    @log_file = "client_logs/client_#{Socket.gethostname}_#{Process.pid}.log"
    FileUtils.touch(@log_file)
  end

  def log(message)
    puts ("[#{Time.now}] #{message}")
    File.open(@log_file, 'a') { |f| f.puts("[#{Time.now}] #{message}") }
  end

  def generate_report
    return if @@return_codes.nil? || @@return_codes.empty?
    log("--- Transfer Summary Report ---")
    log("Total rsync transfers: #{@@return_codes.values.sum}")
    @@return_codes.sort.each do |code, count|
      log("Return Code #{code}: #{count} occurrences")
    end
    log("-------------------------------")
  end

  def send_request(command)
    socket = nil
    begin
      socket = TCPSocket.new(@server, @port)
      if socket.nil?
        @@thread_mutex.synchronize{ @@thread_count -= 1 }
        generate_report if @summary && @@thread_count == 0
        return
      end
      socket.puts command if socket && !socket.closed?
      socket.flush
      response = socket.gets if socket && !socket.closed?
      return JSON.parse(response.chomp) rescue { error: 'Invalid response from server' }

    rescue Errno::ECONNRESET
      return
    rescue StandardError => e
      puts "Unexpeted Error: #{e.lass} - #{e.message}" if @debug
      return
    ensure
      socket.close if socket && !socket.closed?
    end
  end

  def start
    log("Client started, connecting to #{@server}:#{@port}")
    @@return_codes ||= {}
    @@thread_mutex.synchronize{ @@thread_count += 1 }
    loop do
       begin
         response = send_request( {command: 'work'}.to_json )
         if response.nil?
           @@thread_mutex.synchronize{ @@thread_count -= 1 }
           generate_report if @summary && @@thread_count == 0
           return
         end
         if response["status"] == "no work"
           @@thread_mutex.synchronize{ @@thread_count -= 1 }
           generate_report if @summary && @@thread_count == 0
           break
         end

         log("Received task: #{response['identifier']} #{response['path']}")

	 # Write the rsync command to the log file for reference
	 logfile = response['command'].split.last
	 File.open(logfile, 'w') { |f| f.puts("Command: #{response['command']}") }

	 # Perform the rsync
         system(response['command'])
         rc = $?.exitstatus

	 sleep(500) if @debug

         resp = { command: 'done', identifier: response['identifier'], path: response['path'], return_code: rc }.to_json
	 server_response = send_request( resp )

	 @@thread_mutex.synchronize{ @@return_codes[rc] += 1 }
         log("Finished task: #{response['identifier']} #{response['path']} RC: #{rc}")
	 exit 1 if @debug
       rescue Errno::EPIPE
         @@thread_mutex.synchronize{ @@thread_count -= 1 }
         log("Error: Broken pipe - server may have closed connection.")
         return
       rescue Errno::ECONNREFUSED
         @@thread_mutex.synchronize{ @@thread_count -= 1 }
         log("Error: Connection refused. Exiting.")
         return
       rescue StandardError => e
         @@thread_mutex.synchronize{ @@thread_count -= 1 }
         log("Error: #{e.message}")
         return
      end
    end
  end

end

def print_error_report(options)
  server_log = 'server_logs/server.log'

  unless File.exist?(server_log)
    puts "Error: File '#{server_log}' not found."
    return
  end
  File.foreach(server_log) do |line|
    next unless line.include?('RC')
    next if line.include?('RC: 0')
    puts line
  end
end

def display_log(display_type, search_path)
  server_log = 'server_logs/server.log'
  log_found = false  

  File.foreach(server_log) do |line|
    next unless line.include?(search_path)

    log_found = true

    if line.include?('Dispatched')
      fields = line.split
      if fields.length >= 6
        log_token = fields[5]
        log_file = "transfer_logs/transfer_#{log_token}.log"
        puts "Log File: #{log_file}"

        if display_type == 'log'
          system("less #{log_file}")
        elsif display_type == 'tail'
          # This will keep ctrl-c to exit tail from killing script
          pid = spawn("tail -f #{log_file}")
          trap("INT") do
            Process.kill("TERM", pid) rescue nil
            Process.wait(pid) rescue nil
          end

          begin
            Process.wait(pid)
          rescue Errno::ECHILD
            puts ""
          end
        end
        exit 0  # Stop processing after finding a match
      else
        puts "Error: Unable to extract log token."
        exit 1
      end
    end
  end

  # If no match was found, print the message outside the loop
  unless log_found
    puts "Log file for #{search_path} not found."
    exit 1
  end
end

def server_state( options )
  @server = options[:server]
  @port = options[:port]

  begin
    socket = TCPSocket.new(@server, @port)
    socket.puts({command: 'state'}.to_json)
    response = socket.gets
    socket.close
    resp = JSON.parse(response.chomp) rescue { error: 'Invalid response from server' }

    puts "Total Jobs: #{resp['total_xfers']}"
    puts " Remaining: #{resp['left_xfers']}"
    puts "   Clients: #{resp['clients']}"

    puts "\nDispatched jobs:"    
    resp['dispatched'].each do |ip, tokens|
      tokens.each do |token, path|
        puts "#{ip}  #{token}  #{path}"
      end
    end

    puts "\nReturn Code Summary"
    resp['return_codes'].each do |code, count|
      puts "Return Code #{code}: #{count} occurrences"
    end
  rescue Errno::EPIPE
    puts "Error: Broken pipe - server may have closed connection."
    exit 1
  rescue Errno::ECONNREFUSED
    puts "Error: Connection refused. Exiting."
    exit 1
  end
end


if ARGV[0] == 'server'
  if options[:source_dir].nil? || options[:remote_servers].nil? || options[:remote_path].nil?
    puts "Missing server parameters. Use --help for details."
    exit 1
  end
  server = Server.new(options)
  server.start
elsif ARGV[0] == 'client'
  if options[:server].nil?
    puts "Missing client parameters. Use --help for details."
    exit 1
  end

  threads = []

  options[:threads].times do
    threads << Thread.new do
      begin
        client = Client.new(options)
        client.start
      rescue StandardError => e
        puts "Error in thread: #{e.message}"
      end
    end
  end
  threads.each(&:join)
elsif ARGV[0] == 'state'
  server_state(options)
elsif ARGV[0] == 'errors'
  print_error_report(options)
elsif ARGV[0] == 'log' || ARGV[0] == 'tail' 
  if ARGV[1].nil?
    puts "Missing token id or path to search for. Use --help for details."
    exit 1
  end
  display_log( ARGV[0], ARGV[1] )
else
  puts "Usage: psync < server | client | log | tail | task > [options]"
  exit 1
end

