#!/usr/bin/env ruby

require 'socket'
require 'json'
require 'fileutils'
require 'optparse'
require 'securerandom'
require 'socket'

options = { port: 8812 }
OptionParser.new do |opts|
  opts.banner = "Usage: ruby script.rb server [options] | client [options]"
  opts.on("--port PORT", "Server/client port (default: 8812)") { |v| options[:port] = v.to_i }
  opts.on("--source DIR", "Source directory (server)") { |v| options[:source_dir] = v }
  opts.on("--depth DEPTH", "Depth to search (server)") { |v| options[:depth] = v.to_i }
  opts.on("--remote SERVERS", "Comma-separated list of remote servers (server)") { |v| options[:remote_servers] = v.split(',') }
  opts.on("--remote-path PATH", "Remote path for synchronization (server)") { |v| options[:remote_path] = v }
  opts.on("--server-ip IP", "Server IP address (client)") { |v| options[:server_ip] = v }
  opts.on("--debug", "Enable debug mode (server)") { options[:debug] = true }
  opts.on("--help", "Displays help") do
    puts opts
    exit
  end
end.parse!

FileUtils.mkdir_p('server_logs')
FileUtils.mkdir_p('client_logs')
FileUtils.mkdir_p('transfer_logs')

class Server
  def initialize(options)
    @port = options[:port]
    @source_dir = options[:source_dir]
    @depth = options[:depth]
    @remote_servers = options[:remote_servers]
    @remote_path = options[:remote_path]
    @debug = options[:debug]
    @jobs = Queue.new
    @log_file = "server_logs/server.log"
    FileUtils.touch(@log_file)
    @active_clients = 0
    @server_running = true
  end

  def log(message)
    puts message
    File.open(@log_file, 'a') { |f| f.puts("[#{Time.now}] #{message}") }
  end

  def build_jobs
    log("Building job queue...")
    (0..@depth).each do |level|
      dirs = `find #{@source_dir} -mindepth #{level} -maxdepth #{level} -type d`.split("\n")
      dirs.each do |dir|
        relative_path = dir.sub(@source_dir, '').sub(%r{^/}, '')
        @remote_servers.each do |server|
          recursive = (level == @depth) ? '-r' : ''
          identifier = SecureRandom.hex(8)
          log_file = "transfer_logs/transfer_#{identifier}.log"
          rsync_cmd = "rsync -avzHAX --progress #{recursive} #{dir}/ #{server}:#{@remote_path}/#{relative_path}/ &> #{log_file}"
          @jobs.push({ command: rsync_cmd, identifier: identifier, server: server, path: relative_path })
          log("Generated rsync command for #{dir} -> #{server}:#{@remote_path}/#{relative_path} with ID #{identifier}") if @debug
        end
      end
    end
    log("Job queue built with #{@jobs.size} tasks.")
  end

  def start
    Thread.new { build_jobs }
    server = TCPServer.new(@port)
    log("Server started on port #{@port}")
    loop do
      break unless @server_running
      Thread.start(server.accept) do |client|
        if @jobs.empty? && @active_clients == 0
          log("All jobs processed. Shutting down server.")
          @server_running = false
          server.close
          exit
        end
        if @jobs.empty?
          client.puts({ status: 'no work' }.to_json)
          client.close
          next
        end
        job = @jobs.pop
        @active_clients += 1
        log("Assigning job: #{job[:identifier]} (#{job[:path]}) to client at #{client.peeraddr.last}")
        client.puts({ status: 'work', command: job[:command], identifier: job[:identifier], path: job[:path] }.to_json)
        response = client.gets
        if response
          result = JSON.parse(response.chomp)
          log("Client #{client.peeraddr.last} reported: #{result['status']} for job: #{job[:identifier]} (#{job[:path]})")
        end
        @active_clients -= 1
        client.close
      end
    end
  end
end

class Client
  def initialize(options)
    @server = options[:server_ip]
    @port = options[:port]
    hostname = Socket.gethostname
    @log_file = "client_logs/client_#{hostname}_#{SecureRandom.hex(4)}.log"
    FileUtils.touch(@log_file)
  end

  def log(message)
    puts message
    File.open(@log_file, 'a') { |f| f.puts("[#{Time.now}] #{message}") }
  end

  def start
    loop do
      begin
        socket = TCPSocket.open(@server, @port)
        response = socket.gets
        if response.nil?
          log("No response from server. Exiting...")
          socket.close
          break
        end
        parsed_response = JSON.parse(response.chomp)
        if parsed_response['status'] == 'no work'
          log("No work available. Exiting...")
          socket.close
          break
        end
        command = parsed_response['command']
        identifier = parsed_response['identifier']
        path = parsed_response['path']
        log_file = "transfer_logs/transfer_#{identifier}.log"
        log("Executing job #{identifier} (#{path}): #{command}")
        result = system(command)
        status = result ? 'success' : 'failure'
        log("Job #{identifier} (#{path}) completed with status: #{status}")
        socket.puts({ status: status, identifier: identifier }.to_json)
        socket.close
      rescue Errno::ECONNREFUSED
        log("Error: Connection refused. Server might not be running. Exiting...")
        exit 1
      rescue StandardError => e
        log("Error: #{e.message}")
        exit 1
      end
    end
  end
end

if ARGV[0] == 'server'
  if options[:source_dir].nil? || options[:depth].nil? || options[:remote_servers].nil? || options[:remote_path].nil?
    puts "Missing server parameters. Use --help for details."
    exit 1
  end
  server = Server.new(options)
  server.start
elsif ARGV[0] == 'client'
  if options[:server_ip].nil?
    puts "Missing client parameters. Use --help for details."
    exit 1
  end
  client = Client.new(options)
  client.start
else
  puts "Usage: ruby script.rb <server|client> [options]"
  exit 1
end

